export enum Bank {
  KOREA_DEVELOPMENT_BANK = 0,
  IBK_BANK = 1,
  KOOKMIN_BANK = 2,
  KOREA_EXCHANGE_BANK = 3,
  SUHYUP_BANK = 4,
  NH_BANK = 5,
  NH = 6, // Local Corporate
  WOORI_BANK = 7,
  SC_BANK_KOREA = 8,
  SHINHAN_BANK = 9,
  CITI_BANK_KOREA = 10,
  DAEGU_BANK = 11,
  BUSAN_BANK = 12,
  KWANGJU_BANK = 13,
  JEJU_BANK = 14,
  JEONBUK_BANK = 15,
  KYONGNAM_BANK = 16,
  KOREA_FEDERATION_OF_COMMUNITY_CREDIT_COOPERATIVES = 17, // SAEMAEUL_GEUMGO
  NATIONAL_CREDIT_UNION_FEDERATION_OF_KOREA = 18, // SHINHYUP
  KOREA_FEDERATION_OF_SAVINGS_BANKS = 19, // SANGHO_JEOCHUK_BANK
  NATIONAL_FORESTRY_COOPERATIVE_FEDERATION = 20, // SANRIM_JOHAP
  POST_OFFICE = 21,
  K_BANK = 22,
  KEB_HANA_BANK = 23,
  KAKAO_BANK = 24,
  TOSS_BANK = 25,
}
